(function() {
    var myApp = angular.module('myApp');

    myApp.factory('Featured', function(BasePlaylist, SettingService, LanguageService) {

        var FeaturedPlaylist = BasePlaylist.extend({
            getNextData: function() {
                var defer = $.Deferred();
                var that = this;
                if(this.tracks.length > 0){
                    setTimeout(function(){
                        // defer.resolve([]);
                        defer.resolve(that.tracks);
                    }, 0);
                }else{                    
                    var language = SettingService.get('language');
                    var isoLanguage = LanguageService.getISO(language) || 'en';
                    setTimeout(function(){
                        if(isoLanguage === "en"){
                            defer.resolve(english.results);
                        }else {
                            defer.resolve(japanese.results);
                        }
                    }, 1000);
                }
                
                return defer.promise();
            }
        });

        return FeaturedPlaylist;
    });

    var english = {
    "headers": {
        "status": "success",
        "code": 0,
        "error_message": "",
        "warnings": "",
        "results_count": 30,
        "results_fullcount": null
    },
    "results": [{
        "album_id": "130395",
        "duration": 214,
        "id": "1093987",
        "artist_id": "433610",
        "artist_idstr": "Tamara_Laurel",
        "artist_name": "Tamara Laurel",
        "position": 1,
        "album_name": "Lightning",
        "name": "Sweet",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2014-01-07",
        "album_image": "assets/images/albums/s130/130395/covers/1.200.jpg",
        "audio": "audio/1093987_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1093987/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 13915,
            "rate_listened_total": 79044,
            "playlisted": 115,
            "favorited": 66,
            "likes": 33,
            "dislikes": 0,
            "avgnote": 10,
            "notes": 1
        },
        "shorturl": "http://jamen.do/t/1093987",
        "shareurl": "http://www.jamendo.com/track/1093987"
    }, {
        "album_id": "129329",
        "duration": 312,
        "id": "1085325",
        "artist_id": "340555",
        "artist_idstr": "Amity_in_Fame",
        "artist_name": "Amity in Fame",
        "position": 2,
        "album_name": "Through",
        "name": "When It Comes To The End",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2013-12-05",
        "album_image": "assets/images/albums/s129/129329/covers/1.200.jpg",
        "audio": "audio/1085325_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1085325/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1085325",
        "stats": {
            "rate_downloads_total": 17912,
            "rate_listened_total": 117282,
            "playlisted": 108,
            "favorited": 60,
            "likes": 43,
            "dislikes": 1,
            "avgnote": 7,
            "notes": 1
        },
        "shorturl": "http://jamen.do/t/1085325",
        "shareurl": "http://www.jamendo.com/track/1085325"
    }, {
        "album_id": "121316",
        "duration": 206,
        "id": "1031187",
        "artist_id": "433610",
        "artist_idstr": "Tamara_Laurel",
        "artist_name": "Tamara Laurel",
        "position": 1,
        "album_name": "I Want You - Single",
        "name": "I Want You",
        "license_ccurl": "http://creativecommons.org/licenses/by-sa/3.0/",
        "releasedate": "2013-05-03",
        "album_image": "assets/images/albums/s121/121316/covers/1.200.jpg",
        "audio": "audio/1031187_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1031187/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 153149,
            "rate_listened_total": 572396,
            "playlisted": 731,
            "favorited": 419,
            "likes": 158,
            "dislikes": 5,
            "avgnote": 9.625,
            "notes": 8
        },
        "shorturl": "http://jamen.do/t/1031187",
        "shareurl": "http://www.jamendo.com/track/1031187"
    }, {
        "album_id": "128216",
        "duration": 190,
        "id": "1076458",
        "artist_id": "340553",
        "artist_idstr": "Oceansea",
        "artist_name": "Oceansea",
        "position": 2,
        "album_name": "Songs From The Attic Window",
        "name": "Poetry For The Moon",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2013-11-01",
        "album_image": "assets/images/albums/s128/128216/covers/1.200.jpg",
        "audio": "audio/1076458_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1076458/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1076458",
        "stats": {
            "rate_downloads_total": 23409,
            "rate_listened_total": 164122,
            "playlisted": 281,
            "favorited": 199,
            "likes": 86,
            "dislikes": 1,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1076458",
        "shareurl": "http://www.jamendo.com/track/1076458"
    }, {
        "album_id": "124474",
        "duration": 239,
        "id": "1055803",
        "artist_id": "436631",
        "artist_idstr": "Joe_Farren_(2)",
        "artist_name": "Joe Farren",
        "position": 7,
        "album_name": "Open Skies",
        "name": "American Dream",
        "license_ccurl": "http://creativecommons.org/licenses/by-sa/3.0/",
        "releasedate": "2013-08-13",
        "album_image": "assets/images/albums/s124/124474/covers/1.200.jpg",
        "audio": "audio/1055803_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1055803/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1055803",
        "stats": {
            "rate_downloads_total": 97142,
            "rate_listened_total": 401426,
            "playlisted": 207,
            "favorited": 96,
            "likes": 38,
            "dislikes": 1,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1055803",
        "shareurl": "http://www.jamendo.com/track/1055803"
    }, {
        "album_id": "129329",
        "duration": 262,
        "id": "1085328",
        "artist_id": "340555",
        "artist_idstr": "Amity_in_Fame",
        "artist_name": "Amity in Fame",
        "position": 1,
        "album_name": "Through",
        "name": "Good Night and Shut Up",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2013-12-05",
        "album_image": "assets/images/albums/s129/129329/covers/1.200.jpg",
        "audio": "audio/1085328_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1085328/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1085328",
        "stats": {
            "rate_downloads_total": 627,
            "rate_listened_total": 14067,
            "playlisted": 34,
            "favorited": 19,
            "likes": 10,
            "dislikes": 1,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1085328",
        "shareurl": "http://www.jamendo.com/track/1085328"
    }, {
        "album_id": "121829",
        "duration": 191,
        "id": "1035001",
        "artist_id": "340012",
        "artist_idstr": "Floppy_Dee",
        "artist_name": "Floppy Dee",
        "position": 1,
        "album_name": "Swept Clean",
        "name": "Swept Clean",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2013-05-21",
        "album_image": "assets/images/albums/s121/121829/covers/1.200.jpg",
        "audio": "audio/1035001_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1035001/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 35469,
            "rate_listened_total": 267799,
            "playlisted": 215,
            "favorited": 108,
            "likes": 24,
            "dislikes": 4,
            "avgnote": 7.5,
            "notes": 2
        },
        "shorturl": "http://jamen.do/t/1035001",
        "shareurl": "http://www.jamendo.com/track/1035001"
    }, {
        "album_id": "3661",
        "duration": 384,
        "id": "26737",
        "artist_id": "104",
        "artist_idstr": "tryad",
        "artist_name": "Tryad",
        "position": 2,
        "album_name": "Listen",
        "name": "Breathe",
        "license_ccurl": "http://creativecommons.org/licenses/by-sa/2.5/",
        "releasedate": "2006-12-21",
        "album_image": "assets/images/albums/s3/3661/covers/1.200.jpg",
        "audio": "audio/26737_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/26737/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-26737",
        "stats": {
            "rate_downloads_total": 32725,
            "rate_listened_total": 493446,
            "playlisted": 7440,
            "favorited": 4951,
            "likes": 23,
            "dislikes": 2,
            "avgnote": 8,
            "notes": 1
        },
        "shorturl": "http://jamen.do/t/26737",
        "shareurl": "http://www.jamendo.com/track/26737"
    }, {
        "album_id": "3661",
        "duration": 324,
        "id": "26739",
        "artist_id": "104",
        "artist_idstr": "tryad",
        "artist_name": "Tryad",
        "position": 4,
        "album_name": "Listen",
        "name": "Listen",
        "license_ccurl": "http://creativecommons.org/licenses/by-sa/2.5/",
        "releasedate": "2006-12-21",
        "album_image": "assets/images/albums/s3/3661/covers/1.200.jpg",
        "audio": "audio/26739_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/26739/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-26739",
        "stats": {
            "rate_downloads_total": 16968,
            "rate_listened_total": 220437,
            "playlisted": 7065,
            "favorited": 4923,
            "likes": 14,
            "dislikes": 1,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/26739",
        "shareurl": "http://www.jamendo.com/track/26739"
    }, {
        "album_id": "23755",
        "duration": 226,
        "id": "162025",
        "artist_id": "7872",
        "artist_idstr": "joshwoodward",
        "artist_name": "Josh Woodward",
        "position": 2,
        "album_name": "The Simple Life",
        "name": "Go",
        "license_ccurl": "http://creativecommons.org/licenses/by/3.0/",
        "releasedate": "2008-04-23",
        "album_image": "assets/images/albums/s23/23755/covers/1.200.jpg",
        "audio": "audio/162025_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/162025/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-162025",
        "stats": {
            "rate_downloads_total": 25251,
            "rate_listened_total": 337071,
            "playlisted": 1979,
            "favorited": 1098,
            "likes": 19,
            "dislikes": 1,
            "avgnote": 9.0909,
            "notes": 11
        },
        "shorturl": "http://jamen.do/t/162025",
        "shareurl": "http://www.jamendo.com/track/162025"
    }, {
        "album_id": "129329",
        "duration": 208,
        "id": "1085352",
        "artist_id": "340555",
        "artist_idstr": "Amity_in_Fame",
        "artist_name": "Amity in Fame",
        "position": 10,
        "album_name": "Through",
        "name": "The Villain",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2013-12-05",
        "album_image": "assets/images/albums/s129/129329/covers/1.200.jpg",
        "audio": "audio/1085352_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1085352/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1085352",
        "stats": {
            "rate_downloads_total": 181,
            "rate_listened_total": 1927,
            "playlisted": 22,
            "favorited": 9,
            "likes": 6,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1085352",
        "shareurl": "http://www.jamendo.com/track/1085352"
    }, {
        "album_id": "129329",
        "duration": 311,
        "id": "1085330",
        "artist_id": "340555",
        "artist_idstr": "Amity_in_Fame",
        "artist_name": "Amity in Fame",
        "position": 7,
        "album_name": "Through",
        "name": "The Kraken",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2013-12-05",
        "album_image": "assets/images/albums/s129/129329/covers/1.200.jpg",
        "audio": "audio/1085330_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1085330/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1085330",
        "stats": {
            "rate_downloads_total": 226,
            "rate_listened_total": 2967,
            "playlisted": 25,
            "favorited": 11,
            "likes": 9,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1085330",
        "shareurl": "http://www.jamendo.com/track/1085330"
    }, {
        "album_id": "129329",
        "duration": 296,
        "id": "1085331",
        "artist_id": "340555",
        "artist_idstr": "Amity_in_Fame",
        "artist_name": "Amity in Fame",
        "position": 8,
        "album_name": "Through",
        "name": "Through",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2013-12-05",
        "album_image": "assets/images/albums/s129/129329/covers/1.200.jpg",
        "audio": "audio/1085331_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1085331/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1085331",
        "stats": {
            "rate_downloads_total": 215,
            "rate_listened_total": 2197,
            "playlisted": 24,
            "favorited": 11,
            "likes": 6,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1085331",
        "shareurl": "http://www.jamendo.com/track/1085331"
    }, {
        "album_id": "3661",
        "duration": 313,
        "id": "26741",
        "artist_id": "104",
        "artist_idstr": "tryad",
        "artist_name": "Tryad",
        "position": 6,
        "album_name": "Listen",
        "name": "Lovely",
        "license_ccurl": "http://creativecommons.org/licenses/by-sa/2.5/",
        "releasedate": "2006-12-21",
        "album_image": "assets/images/albums/s3/3661/covers/1.200.jpg",
        "audio": "audio/26741_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/26741/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-26741",
        "stats": {
            "rate_downloads_total": 16156,
            "rate_listened_total": 166570,
            "playlisted": 6946,
            "favorited": 4915,
            "likes": 16,
            "dislikes": 1,
            "avgnote": 9,
            "notes": 1
        },
        "shorturl": "http://jamen.do/t/26741",
        "shareurl": "http://www.jamendo.com/track/26741"
    }, {
        "album_id": "129329",
        "duration": 124,
        "id": "1085353",
        "artist_id": "340555",
        "artist_idstr": "Amity_in_Fame",
        "artist_name": "Amity in Fame",
        "position": 11,
        "album_name": "Through",
        "name": "World Is In",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2013-12-05",
        "album_image": "assets/images/albums/s129/129329/covers/1.200.jpg",
        "audio": "audio/1085353_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1085353/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1085353",
        "stats": {
            "rate_downloads_total": 87,
            "rate_listened_total": 1842,
            "playlisted": 22,
            "favorited": 10,
            "likes": 6,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1085353",
        "shareurl": "http://www.jamendo.com/track/1085353"
    }, {
        "album_id": "129329",
        "duration": 299,
        "id": "1085332",
        "artist_id": "340555",
        "artist_idstr": "Amity_in_Fame",
        "artist_name": "Amity in Fame",
        "position": 9,
        "album_name": "Through",
        "name": "Burning The Witch",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2013-12-05",
        "album_image": "assets/images/albums/s129/129329/covers/1.200.jpg",
        "audio": "audio/1085332_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1085332/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1085332",
        "stats": {
            "rate_downloads_total": 219,
            "rate_listened_total": 7782,
            "playlisted": 20,
            "favorited": 8,
            "likes": 6,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1085332",
        "shareurl": "http://www.jamendo.com/track/1085332"
    }, {
        "album_id": "129329",
        "duration": 321,
        "id": "1085351",
        "artist_id": "340555",
        "artist_idstr": "Amity_in_Fame",
        "artist_name": "Amity in Fame",
        "position": 5,
        "album_name": "Through",
        "name": "Cyranoia",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2013-12-05",
        "album_image": "assets/images/albums/s129/129329/covers/1.200.jpg",
        "audio": "audio/1085351_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1085351/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1085351",
        "stats": {
            "rate_downloads_total": 143,
            "rate_listened_total": 3143,
            "playlisted": 23,
            "favorited": 10,
            "likes": 6,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1085351",
        "shareurl": "http://www.jamendo.com/track/1085351"
    }, {
        "album_id": "129329",
        "duration": 122,
        "id": "1085327",
        "artist_id": "340555",
        "artist_idstr": "Amity_in_Fame",
        "artist_name": "Amity in Fame",
        "position": 4,
        "album_name": "Through",
        "name": "Saint",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2013-12-05",
        "album_image": "assets/images/albums/s129/129329/covers/1.200.jpg",
        "audio": "audio/1085327_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1085327/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-1085327",
        "stats": {
            "rate_downloads_total": 176,
            "rate_listened_total": 3253,
            "playlisted": 21,
            "favorited": 9,
            "likes": 5,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1085327",
        "shareurl": "http://www.jamendo.com/track/1085327"
    }, {
        "album_id": "47305",
        "duration": 283,
        "id": "366748",
        "artist_id": "351202",
        "artist_idstr": "felixjd",
        "artist_name": "Felixjd",
        "position": 1,
        "album_name": "Y  Love House",
        "name": "felixjd - _make_believe_",
        "license_ccurl": "http://creativecommons.org/licenses/by/3.0/",
        "releasedate": "2009-06-15",
        "album_image": "assets/images/albums/s47/47305/covers/1.200.jpg",
        "audio": "audio/366748_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/366748/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-366748",
        "stats": {
            "rate_downloads_total": 33800,
            "rate_listened_total": 361331,
            "playlisted": 353,
            "favorited": 105,
            "likes": 8,
            "dislikes": 1,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/366748",
        "shareurl": "http://www.jamendo.com/track/366748"
    }, {
        "album_id": "7505",
        "duration": 312,
        "id": "81740",
        "artist_id": "8303",
        "artist_idstr": "pornophonique",
        "artist_name": "pornophonique",
        "position": 1,
        "album_name": "8-bit lagerfeuer",
        "name": "sad robot",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/2.0/de/",
        "releasedate": "2007-09-06",
        "album_image": "assets/images/albums/s7/7505/covers/1.200.jpg",
        "audio": "audio/81740_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/81740/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-81740",
        "stats": {
            "rate_downloads_total": 50539,
            "rate_listened_total": 707709,
            "playlisted": 6902,
            "favorited": 4217,
            "likes": 55,
            "dislikes": 0,
            "avgnote": 9,
            "notes": 5
        },
        "shorturl": "http://jamen.do/t/81740",
        "shareurl": "http://www.jamendo.com/track/81740"
    }, {
        "album_id": "3661",
        "duration": 326,
        "id": "26745",
        "artist_id": "104",
        "artist_idstr": "tryad",
        "artist_name": "Tryad",
        "position": 10,
        "album_name": "Listen",
        "name": "All the Same",
        "license_ccurl": "http://creativecommons.org/licenses/by-sa/2.5/",
        "releasedate": "2006-12-21",
        "album_image": "assets/images/albums/s3/3661/covers/1.200.jpg",
        "audio": "audio/26745_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/26745/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-26745",
        "stats": {
            "rate_downloads_total": 7013,
            "rate_listened_total": 105605,
            "playlisted": 6762,
            "favorited": 4887,
            "likes": 10,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/26745",
        "shareurl": "http://www.jamendo.com/track/26745"
    }, {
        "album_id": "116452",
        "duration": 203,
        "id": "989873",
        "artist_id": "357359",
        "artist_idstr": "Kellee_Maize",
        "artist_name": "Kellee Maize",
        "position": 3,
        "album_name": "Owl Time",
        "name": "Owl Time",
        "license_ccurl": "http://creativecommons.org/licenses/by-sa/3.0/",
        "releasedate": "2012-12-18",
        "album_image": "assets/images/albums/s116/116452/covers/1.200.jpg",
        "audio": "audio/989873_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/989873/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-989873",
        "stats": {
            "rate_downloads_total": 71465,
            "rate_listened_total": 378730,
            "playlisted": 212,
            "favorited": 112,
            "likes": 15,
            "dislikes": 4,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/989873",
        "shareurl": "http://www.jamendo.com/track/989873"
    }, {
        "album_id": "41593",
        "duration": 260,
        "id": "306166",
        "artist_id": "348487",
        "artist_idstr": "Stephane_TV",
        "artist_name": "Stephane TV",
        "position": 2,
        "album_name": "s/t (ep)",
        "name": "See The Ghosts",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2009-03-09",
        "album_image": "assets/images/albums/s41/41593/covers/1.200.jpg",
        "audio": "audio/306166_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/306166/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-306166",
        "stats": {
            "rate_downloads_total": 3997,
            "rate_listened_total": 104652,
            "playlisted": 143,
            "favorited": 96,
            "likes": 9,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/306166",
        "shareurl": "http://www.jamendo.com/track/306166"
    }, {
        "album_id": "6450",
        "duration": 256,
        "id": "73068",
        "artist_id": "7349",
        "artist_idstr": "cartel",
        "artist_name": "Cartel",
        "position": 11,
        "album_name": "Prepare For Glory",
        "name": "I Remember When by Gates",
        "license_ccurl": "http://creativecommons.org/licenses/by-sa/3.0/",
        "releasedate": "2007-07-07",
        "album_image": "assets/images/albums/s6/6450/covers/1.200.jpg",
        "audio": "audio/73068_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/73068/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-73068",
        "stats": {
            "rate_downloads_total": 2379,
            "rate_listened_total": 28186,
            "playlisted": 453,
            "favorited": 282,
            "likes": 4,
            "dislikes": 3,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/73068",
        "shareurl": "http://www.jamendo.com/track/73068"
    }, {
        "album_id": "7505",
        "duration": 206,
        "id": "81743",
        "artist_id": "8303",
        "artist_idstr": "pornophonique",
        "artist_name": "pornophonique",
        "position": 4,
        "album_name": "8-bit lagerfeuer",
        "name": "space invaders",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/2.0/de/",
        "releasedate": "2007-09-06",
        "album_image": "assets/images/albums/s7/7505/covers/1.200.jpg",
        "audio": "audio/81743_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/81743/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-81743",
        "stats": {
            "rate_downloads_total": 12787,
            "rate_listened_total": 151394,
            "playlisted": 5544,
            "favorited": 4072,
            "likes": 11,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/81743",
        "shareurl": "http://www.jamendo.com/track/81743"
    }, {
        "album_id": "7505",
        "duration": 312,
        "id": "81742",
        "artist_id": "8303",
        "artist_idstr": "pornophonique",
        "artist_name": "pornophonique",
        "position": 3,
        "album_name": "8-bit lagerfeuer",
        "name": "lemmings in love",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/2.0/de/",
        "releasedate": "2007-09-06",
        "album_image": "assets/images/albums/s7/7505/covers/1.200.jpg",
        "audio": "audio/81742_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/81742/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-81742",
        "stats": {
            "rate_downloads_total": 9821,
            "rate_listened_total": 247873,
            "playlisted": 5485,
            "favorited": 4061,
            "likes": 10,
            "dislikes": 2,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/81742",
        "shareurl": "http://www.jamendo.com/track/81742"
    }, {
        "album_id": "89160",
        "duration": 399,
        "id": "761836",
        "artist_id": "343607",
        "artist_idstr": "Tunguska_Chillout_Grooves_vol.1",
        "artist_name": "Tunguska Electronic Music Society",
        "position": 4,
        "album_name": "Tunguska Chillout Grooves Vol. 7",
        "name": "Aquascape - Sunrise",
        "license_ccurl": "http://creativecommons.org/licenses/by-nd/3.0/",
        "releasedate": "2011-04-11",
        "album_image": "assets/images/albums/s89/89160/covers/1.200.jpg",
        "audio": "audio/761836_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/761836/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-761836",
        "stats": {
            "rate_downloads_total": 37754,
            "rate_listened_total": 151676,
            "playlisted": 686,
            "favorited": 321,
            "likes": 21,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/761836",
        "shareurl": "http://www.jamendo.com/track/761836"
    }, {
        "album_id": "82013",
        "duration": 369,
        "id": "703364",
        "artist_id": "351337",
        "artist_idstr": "SINGLETON",
        "artist_name": "Singleton",
        "position": 4,
        "album_name": "The High Seas",
        "name": "If I'm Falling",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2010-12-22",
        "album_image": "assets/images/albums/s82/82013/covers/1.200.jpg",
        "audio": "audio/703364_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/703364/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-703364",
        "stats": {
            "rate_downloads_total": 15291,
            "rate_listened_total": 44481,
            "playlisted": 490,
            "favorited": 317,
            "likes": 13,
            "dislikes": 1,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/703364",
        "shareurl": "http://www.jamendo.com/track/703364"
    }, {
        "album_id": "111863",
        "duration": 239,
        "id": "951449",
        "artist_id": "354307",
        "artist_idstr": "Ay-14ice",
        "artist_name": "Ay - 14ice",
        "position": 1,
        "album_name": "Ay-14ice - Show Me What You Got",
        "name": "Ay-14ice - Never Love Again",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2012-07-14",
        "album_image": "assets/images/albums/s111/111863/covers/1.200.jpg",
        "audio": "audio/951449_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/951449/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-951449",
        "stats": {
            "rate_downloads_total": 27486,
            "rate_listened_total": 149091,
            "playlisted": 249,
            "favorited": 141,
            "likes": 10,
            "dislikes": 1,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/951449",
        "shareurl": "http://www.jamendo.com/track/951449"
    }, {
        "album_id": "3661",
        "duration": 256,
        "id": "26738",
        "artist_id": "104",
        "artist_idstr": "tryad",
        "artist_name": "Tryad",
        "position": 3,
        "album_name": "Listen",
        "name": "Alone",
        "license_ccurl": "http://creativecommons.org/licenses/by-sa/2.5/",
        "releasedate": "2006-12-21",
        "album_image": "assets/images/albums/s3/3661/covers/1.200.jpg",
        "audio": "audio/26738_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/26738/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-26738",
        "stats": {
            "rate_downloads_total": 13820,
            "rate_listened_total": 258649,
            "playlisted": 7024,
            "favorited": 4914,
            "likes": 15,
            "dislikes": 1,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/26738",
        "shareurl": "http://www.jamendo.com/track/26738"
    }
    ]
};

var japanese = {
    "headers": {
        "status": "success",
        "code": 0,
        "error_message": "",
        "warnings": "",
        "results_count": 22,
        "results_fullcount": null
    },
    "results": [{
        "album_id": "113987",
        "duration": 200,
        "id": "968840",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 1,
        "album_name": "Nakimushi Butterfly",
        "name": "Nakimushi Butterfly",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2012-09-27",
        "album_image": "assets/images/albums/s113/113987/covers/1.200.jpg",
        "audio": "audio/968840_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/968840/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 1415,
            "rate_listened_total": 4986,
            "playlisted": 16,
            "favorited": 7,
            "likes": 2,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/968840",
        "shareurl": "http://www.jamendo.com/track/968840"
    }, {
        "album_id": "124185",
        "duration": 204,
        "id": "1053814",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 2,
        "album_name": "Renkyori - Love distance",
        "name": "Shiny day!!",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2013-08-04",
        "album_image": "assets/images/albums/s124/124185/covers/1.200.jpg",
        "audio": "audio/1053814_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1053814/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 213,
            "rate_listened_total": 1239,
            "playlisted": 1,
            "favorited": 0,
            "likes": 0,
            "dislikes": 0,
            "avgnote": 7,
            "notes": 1
        },
        "shorturl": "http://jamen.do/t/1053814",
        "shareurl": "http://www.jamendo.com/track/1053814"
    }, {
        "album_id": "116078",
        "duration": 228,
        "id": "986220",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 1,
        "album_name": "Sora - the sky",
        "name": "sora - the sky",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2012-12-07",
        "album_image": "assets/images/albums/s116/116078/covers/1.200.jpg",
        "audio": "audio/986220_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/986220/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 2351,
            "rate_listened_total": 8953,
            "playlisted": 20,
            "favorited": 8,
            "likes": 5,
            "dislikes": 0,
            "avgnote": 10,
            "notes": 1
        },
        "shorturl": "http://jamen.do/t/986220",
        "shareurl": "http://www.jamendo.com/track/986220"
    }, {
        "album_id": "124185",
        "duration": 232,
        "id": "1053815",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 1,
        "album_name": "Renkyori - Love distance",
        "name": "Renkyori - Love distance",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2013-08-04",
        "album_image": "assets/images/albums/s124/124185/covers/1.200.jpg",
        "audio": "audio/1053815_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1053815/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 147,
            "rate_listened_total": 1175,
            "playlisted": 1,
            "favorited": 0,
            "likes": 0,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1053815",
        "shareurl": "http://www.jamendo.com/track/1053815"
    }, {
        "album_id": "113985",
        "duration": 254,
        "id": "968836",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 1,
        "album_name": "A flower blooms",
        "name": "A flower blooms",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2012-09-27",
        "album_image": "assets/images/albums/s113/113985/covers/1.200.jpg",
        "audio": "audio/968836_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/968836/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 1342,
            "rate_listened_total": 3925,
            "playlisted": 6,
            "favorited": 3,
            "likes": 1,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/968836",
        "shareurl": "http://www.jamendo.com/track/968836"
    }, {
        "album_id": "123476",
        "duration": 240,
        "id": "1047823",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 5,
        "album_name": "1st Mini Album",
        "name": "The highest",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2013-07-14",
        "album_image": "assets/images/albums/s123/123476/covers/1.200.jpg",
        "audio": "audio/1047823_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1047823/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 332,
            "rate_listened_total": 1981,
            "playlisted": 4,
            "favorited": 2,
            "likes": 1,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1047823",
        "shareurl": "http://www.jamendo.com/track/1047823"
    }, {
        "album_id": "28951",
        "duration": 288,
        "id": "193745",
        "artist_id": "340779",
        "artist_idstr": "CC_Asia_Band",
        "artist_name": "CC Asia Band",
        "position": 1,
        "album_name": "CABACA",
        "name": "Lim Giong - CABACA - Bosom",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/2.5/tw/",
        "releasedate": "2008-07-23",
        "album_image": "assets/images/albums/s28/28951/covers/1.200.jpg",
        "audio": "audio/193745_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/193745/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 1186,
            "rate_listened_total": 8750,
            "playlisted": 27,
            "favorited": 14,
            "likes": 1,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/193745",
        "shareurl": "http://www.jamendo.com/track/193745"
    }, {
        "album_id": "77905",
        "duration": 277,
        "id": "671601",
        "artist_id": "364006",
        "artist_idstr": "Toshinori_Murashima",
        "artist_name": "Toshinori Murashima",
        "position": 1,
        "album_name": "Noise to Taion (Noise and Temperature)",
        "name": "Red",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2010-10-23",
        "album_image": "assets/images/albums/s77/77905/covers/1.200.jpg",
        "audio": "audio/671601_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/671601/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-671601",
        "stats": {
            "rate_downloads_total": 479,
            "rate_listened_total": 3226,
            "playlisted": 21,
            "favorited": 10,
            "likes": 0,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/671601",
        "shareurl": "http://www.jamendo.com/track/671601"
    }, {
        "album_id": "1141",
        "duration": 327,
        "id": "7541",
        "artist_id": "951",
        "artist_idstr": "arietys",
        "artist_name": "Arietys",
        "position": 1,
        "album_name": "Humanit\u00e9",
        "name": "Mydgard Spirits (Arietys Opening)",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2006-02-06",
        "album_image": "assets/images/albums/s1/1141/covers/1.200.jpg",
        "audio": "audio/7541_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/7541/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 834,
            "rate_listened_total": 21882,
            "playlisted": 392,
            "favorited": 316,
            "likes": 1,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/7541",
        "shareurl": "http://www.jamendo.com/track/7541"
    }, {
        "album_id": "79925",
        "duration": 234,
        "id": "686505",
        "artist_id": "364746",
        "artist_idstr": "Phrenia",
        "artist_name": "Phrenia",
        "position": 1,
        "album_name": "Phrenia",
        "name": "Dilemma",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2010-11-22",
        "album_image": "assets/images/albums/s79/79925/covers/1.200.jpg",
        "audio": "audio/686505_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/686505/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-686505",
        "stats": {
            "rate_downloads_total": 2497,
            "rate_listened_total": 22458,
            "playlisted": 207,
            "favorited": 128,
            "likes": 4,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/686505",
        "shareurl": "http://www.jamendo.com/track/686505"
    }, {
        "album_id": "114583",
        "duration": 256,
        "id": "973281",
        "artist_id": "369454",
        "artist_idstr": "Iced_Blade",
        "artist_name": "Iced Blade",
        "position": 1,
        "album_name": "Chiru Hana",
        "name": "Chiru Hana ft.lily-an",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2012-10-17",
        "album_image": "assets/images/albums/s114/114583/covers/1.200.jpg",
        "audio": "audio/973281_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/973281/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-973281",
        "stats": {
            "rate_downloads_total": 828,
            "rate_listened_total": 2514,
            "playlisted": 22,
            "favorited": 14,
            "likes": 2,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/973281",
        "shareurl": "http://www.jamendo.com/track/973281"
    }, {
        "album_id": "115899",
        "duration": 351,
        "id": "984653",
        "artist_id": "369454",
        "artist_idstr": "Iced_Blade",
        "artist_name": "Iced Blade",
        "position": 1,
        "album_name": "Firn -the pale sun- ft.lily-an/Maya Full",
        "name": "Firn -the pale sun- ft.lily-an/Maya Full",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
        "releasedate": "2012-12-01",
        "album_image": "assets/images/albums/s115/115899/covers/1.200.jpg",
        "audio": "audio/984653_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/984653/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-984653",
        "stats": {
            "rate_downloads_total": 1476,
            "rate_listened_total": 8848,
            "playlisted": 66,
            "favorited": 36,
            "likes": 8,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/984653",
        "shareurl": "http://www.jamendo.com/track/984653"
    }, {
        "album_id": "29044",
        "duration": 43,
        "id": "194433",
        "artist_id": "340779",
        "artist_idstr": "CC_Asia_Band",
        "artist_name": "CC Asia Band",
        "position": 5,
        "album_name": "CABACA-3 : (SAPORRO I-SUMMIT 2008 SEASON LIMITED) (CD 17-21).[\u5361\u5df4",
        "name": "21.Song Of Hokkaido(\u5317\u6d77\u9053\u4e4b\u6b4c)",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/2.5/tw/",
        "releasedate": "2008-07-25",
        "album_image": "assets/images/albums/s29/29044/covers/1.200.jpg",
        "audio": "audio/194433_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/194433/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 806,
            "rate_listened_total": 8372,
            "playlisted": 11,
            "favorited": 7,
            "likes": 0,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/194433",
        "shareurl": "http://www.jamendo.com/track/194433"
    }, {
        "album_id": "29044",
        "duration": 21,
        "id": "194422",
        "artist_id": "340779",
        "artist_idstr": "CC_Asia_Band",
        "artist_name": "CC Asia Band",
        "position": 2,
        "album_name": "CABACA-3 : (SAPORRO I-SUMMIT 2008 SEASON LIMITED) (CD 17-21).[\u5361\u5df4",
        "name": "18.Saporro ! I-Summit !(\u672d\u5e4c.\u6211.\u9ad8\u5cf0)",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/2.5/tw/",
        "releasedate": "2008-07-25",
        "album_image": "assets/images/albums/s29/29044/covers/1.200.jpg",
        "audio": "audio/194422_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/194422/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 362,
            "rate_listened_total": 5509,
            "playlisted": 5,
            "favorited": 2,
            "likes": 0,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/194422",
        "shareurl": "http://www.jamendo.com/track/194422"
    }, {
        "album_id": "123476",
        "duration": 234,
        "id": "1047826",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 4,
        "album_name": "1st Mini Album",
        "name": "Orange lemonade",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2013-07-14",
        "album_image": "assets/images/albums/s123/123476/covers/1.200.jpg",
        "audio": "audio/1047826_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1047826/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 348,
            "rate_listened_total": 1663,
            "playlisted": 3,
            "favorited": 0,
            "likes": 1,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1047826",
        "shareurl": "http://www.jamendo.com/track/1047826"
    }, {
        "album_id": "123476",
        "duration": 265,
        "id": "1047824",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 1,
        "album_name": "1st Mini Album",
        "name": "Sweet heart",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2013-07-14",
        "album_image": "assets/images/albums/s123/123476/covers/1.200.jpg",
        "audio": "audio/1047824_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1047824/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 306,
            "rate_listened_total": 1903,
            "playlisted": 2,
            "favorited": 0,
            "likes": 1,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1047824",
        "shareurl": "http://www.jamendo.com/track/1047824"
    }, {
        "album_id": "29081",
        "duration": 22,
        "id": "194733",
        "artist_id": "340779",
        "artist_idstr": "CC_Asia_Band",
        "artist_name": "CC Asia Band",
        "position": 6,
        "album_name": "CABACA-5",
        "name": "CC Asia Band - CABACA - 37 Thank You Very Much",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/2.5/tw/",
        "releasedate": "2008-07-26",
        "album_image": "assets/images/albums/s29/29081/covers/1.200.jpg",
        "audio": "audio/194733_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/194733/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 274,
            "rate_listened_total": 2868,
            "playlisted": 3,
            "favorited": 2,
            "likes": 0,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/194733",
        "shareurl": "http://www.jamendo.com/track/194733"
    }, {
        "album_id": "54787",
        "duration": 465,
        "id": "459148",
        "artist_id": "7051",
        "artist_idstr": "grunemusik",
        "artist_name": "Gr\u00fcnemusik",
        "position": 3,
        "album_name": "WX Single",
        "name": "WX",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-sa/2.1/jp/",
        "releasedate": "2009-11-03",
        "album_image": "assets/images/albums/s54/54787/covers/1.200.jpg",
        "audio": "audio/459148_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/459148/mp32/?from=app-615ea00d",
        "prourl": "https://pro.jamendo.com/royalty-free-music-library#search=track-459148",
        "stats": {
            "rate_downloads_total": 47,
            "rate_listened_total": 1149,
            "playlisted": 7,
            "favorited": 3,
            "likes": 0,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/459148",
        "shareurl": "http://www.jamendo.com/track/459148"
    }, {
        "album_id": "123476",
        "duration": 217,
        "id": "1047827",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 3,
        "album_name": "1st Mini Album",
        "name": "We are rock!!",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2013-07-14",
        "album_image": "assets/images/albums/s123/123476/covers/1.200.jpg",
        "audio": "audio/1047827_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1047827/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 573,
            "rate_listened_total": 3530,
            "playlisted": 8,
            "favorited": 3,
            "likes": 2,
            "dislikes": 0,
            "avgnote": 8,
            "notes": 1
        },
        "shorturl": "http://jamen.do/t/1047827",
        "shareurl": "http://www.jamendo.com/track/1047827"
    }, {
        "album_id": "123476",
        "duration": 220,
        "id": "1047825",
        "artist_id": "425668",
        "artist_idstr": "WhiteCatsEye",
        "artist_name": "Shironeko",
        "position": 2,
        "album_name": "1st Mini Album",
        "name": "Hohoemi braver",
        "license_ccurl": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
        "releasedate": "2013-07-14",
        "album_image": "assets/images/albums/s123/123476/covers/1.200.jpg",
        "audio": "audio/1047825_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1047825/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 321,
            "rate_listened_total": 1513,
            "playlisted": 2,
            "favorited": 0,
            "likes": 1,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1047825",
        "shareurl": "http://www.jamendo.com/track/1047825"
    }, {
        "album_id": "130574",
        "duration": 98,
        "id": "1095252",
        "artist_id": "357163",
        "artist_idstr": "Ambient_Samurai_-_Ichiro_NAKAGAWA",
        "artist_name": "Ambient Samurai - Ichiro NAKAGAWA",
        "position": 5,
        "album_name": "Live At Shibuya Last Waltz Incident At A Street Corner \u30e9\u30a4\u30d6\u3000\u6e0b\u8c37\u30e9\u30b9\u30c8",
        "name": "Song For Galaxy Observers\u3000 \u3000\u3000\u9280\u6cb3\u306e\u898b\u3048\u308b\u6240\u3078",
        "license_ccurl": "http://creativecommons.org/licenses/by/3.0/",
        "releasedate": "2014-01-13",
        "album_image": "assets/images/albums/s130/130574/covers/1.200.jpg",
        "audio": "audio/1095252_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1095252/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 0,
            "rate_listened_total": 107,
            "playlisted": 0,
            "favorited": 0,
            "likes": 0,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1095252",
        "shareurl": "http://www.jamendo.com/track/1095252"
    }, {
        "album_id": "130574",
        "duration": 129,
        "id": "1095251",
        "artist_id": "357163",
        "artist_idstr": "Ambient_Samurai_-_Ichiro_NAKAGAWA",
        "artist_name": "Ambient Samurai - Ichiro NAKAGAWA",
        "position": 2,
        "album_name": "Live At Shibuya Last Waltz Incident At A Street Corner \u30e9\u30a4\u30d6\u3000\u6e0b\u8c37\u30e9\u30b9\u30c8",
        "name": "Song For No Blood Of No Sea\u3000 \u3000\u3000\u8840\u3092\u6d41\u3055\u305a\u3001\u6d77\u3092\u9694\u3066\u305a",
        "license_ccurl": "http://creativecommons.org/licenses/by/3.0/",
        "releasedate": "2014-01-13",
        "album_image": "assets/images/albums/s130/130574/covers/1.200.jpg",
        "audio": "audio/1095251_96.mp3",
        "audiodownload": "http://storage-new.newjamendo.com/download/track/1095251/mp32/?from=app-615ea00d",
        "stats": {
            "rate_downloads_total": 0,
            "rate_listened_total": 84,
            "playlisted": 0,
            "favorited": 0,
            "likes": 0,
            "dislikes": 0,
            "avgnote": 0,
            "notes": 0
        },
        "shorturl": "http://jamen.do/t/1095251",
        "shareurl": "http://www.jamendo.com/track/1095251"
    }
    ]
};


})();


